### ISSUE TITLE
CWS Extension Updates Failed (Related to having too many extensions?)

### ISSUE THREAD

**Issue by jacobmix** [NeverDecaf/chromium-web-store#169]
Here's what i get from console (shortened):
```
clients2.google.com/service/update2/crx?response=updatecheck&acceptformat=crx2,crx3&prodversion=139.0.0.0&x=id%<ID_HERE>&x=id%<ID_HERE>&x=id%<...>:1  Failed to load resource: the server responded with a status of 400 ()
util.js:308 Error updating extension [CWS Extensions]: undefined
(anonymous) @ util.js:308
```
Would make sense. If i go to the link i get:
> Bad Request
> Error 400

But if i remove most of the url, and only keep 10 IDs it gives me an actual XML.
I do have 200+ extensions. Started going through disabling, deleting or ignore some.

**Comment by NeverDecaf** [comment]
This should be fixed in [1.5.5.1](https://github.com/NeverDecaf/chromium-web-store/releases/tag/v1.5.5.1) but I can't test it personally. If this fixes it for you please let me know (or close the issue), thanks.

**Comment by jacobmix** [comment]
Tested, and seems to work without issue. Thanks for the fix, and extension as a whole. 👍

**Comment by DanAykroyd256** [comment]
Thanks for looking into this.

I installed the update and the error persists. Disabled, then re-enabled the extension and it's still the same. Went to check the version in the Browser Extensions tab and it still says 1.5.5... is that OK? Should it report as 1.5.5.1?

<img width="1344" height="524" alt="Image" src="https://github.com/user-attachments/assets/aa79d0e0-523b-4cfb-8a8b-e0b709a7ec47" />

I installed the update twice but it's still the same. Thanks.

**Comment by NeverDecaf** [comment]
It should show the correct version number (1.5.5.1). Try completely removing and reinstalling the extension as updates can be weird, especially if you installed via "Load unpacked."

**Comment by jacobmix** [comment]
If you can't get it to work. Try to completely close down the browser after updating, and then should work when you re-open it.

**Comment by DanAykroyd256** [comment]
Thanks, I've restarted Chromium (I'm using Ungoogled-Chromium), reinstalled from scratch, now I see the correct version (1.5.5.1) but the error still persists there; the "?" question mark and the CWS error message are still present.

Any ideas @NeverDecaf? Thanks.

**Comment by NeverDecaf** [comment]
Right click the badge and choose `Inspect popup`. Besides console output the network tab may prove insightful as historically this kind of issue has been caused by a firewall or other method of blocking network requests.

**Comment by DanAykroyd256** [comment]
Thanks @NeverDecaf. I'm seeing the following issues; don't know if they might be related to something being blocked. The extension has been working perfectly for months and never saw this error until the first time I had the update a couple of weeks ago and then this error started and never went away, that is way I was associating this having something to do with the update.

```
Access to fetch at 'https://clients2.google.com/service/update2/crx?response=updatecheck&acceptformat=crx2,crx3&prodversion=139.0.0.0&x=id%3Dbnmojkbbkkonlmlfgejehefjldooiedp%26uc&x=id%3Dcdglnehniifkbagbbombnjghhcihifij%26uc&x=id%3Dhhdobjgopfphlmjbmnpglhfcgppchgje%26uc&x=id%3Dnanobjnbcapkhbkbaffmclfoebfjlbjj%26uc&x=id%3Dnngceckbapebfimnlniiiahkandclblb%26uc' from origin 'chrome-extension://ocaahdebbfolfmndjeplogmgcagdmblk' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
util.js:225  GET https://clients2.google.com/service/update2/crx?response=updatecheck&acceptformat=crx2,crx3&prodversion=139.0.0.0&x=id%3Dbnmojkbbkkonlmlfgejehefjldooiedp%26uc&x=id%3Dcdglnehniifkbagbbombnjghhcihifij%26uc&x=id%3Dhhdobjgopfphlmjbmnpglhfcgppchgje%26uc&x=id%3Dnanobjnbcapkhbkbaffmclfoebfjlbjj%26uc&x=id%3Dnngceckbapebfimnlniiiahkandclblb%26uc net::ERR_FAILED 200 (OK)
(anonymous) @ util.js:225
update_extension @ util.js:224
(anonymous) @ util.js:352
(anonymous) @ util.js:351
util.js:323 Error updating extension [CWS Extensions]: TypeError: Failed to fetch
    at util.js:225:25
    at new Promise (<anonymous>)
    at update_extension (util.js:224:28)
    at util.js:352:33
    at Array.map (<anonymous>)
    at util.js:351:30
(anonymous) @ util.js:323
Promise.catch
(anonymous) @ util.js:322
update_extension @ util.js:224
(anonymous) @ util.js:352
(anonymous) @ util.js:351
```

**Comment by NeverDecaf** [comment]
My gut tells me something in your environment is tampering with the requests. Could be another browser extension, antivirus, VPN, network wide filtering, browser setting, etc. If you want to debug it yourself then I would try the following, in order:
Opening the `https://clients2.google.com/service/update2...` url directly in your browser and see if it loads
Disable all your other extensions, especially any that edit network requests
Try on a fresh chromium install with a fresh profile and only 0-1 other extension from the web store
The network tab in `inspect popup` *may* offer more insight

Regardless, please open a new issue if you can't solve this as it is more likely another user will see it and may offer a solution.

**Comment by DanAykroyd256** [comment]
Thanks @NeverDecaf and that's a good starting point; it might be AdGuard that messes with the requests. What surprised me is that the exact same setup has been working perfectly for months; as soon as I updated the extension (the only time I got an update in about a year), it broke instantly. I'll open a new issue soon

**Comment by arrowgent** [comment]
be sure nothing is blocking `clients2.google.com` such as a hosts file, dns blocker, etc.
